// Generated by CoffeeScript 1.6.3
var Game,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Game = (function(_super) {
  __extends(Game, _super);

  function Game(parent, data_bus) {
    this.parent = parent;
    this.data_bus = data_bus;
    this.register_commands = null;
    this.register_variables = null;
    this.register_events = {
      "game_ready": [],
      "game_view_done": []
    };
    this.messages = {
      "null": null
    };
    Game.__super__.constructor.call(this, "game");
    this.game_board = new Board(this, this.data_bus);
    this.game_status = new GameStatus(this, this.data_bus);
    this.data_bus.databus_subscribe_to_event("end_game", this);
    return;
  }

  Game.prototype.render = function(target_element) {
    this.game_status.render(this.main_element);
    this.game_board.render(this.main_element, true);
    target_element.html(this.main_element);
    this.raise_event("game_ready");
  };

  Game.prototype.event_notify = function(event_name) {
    console.log("Game ended!");
    return this.raise_event("game_view_done");
  };

  return Game;

})(View);
